# App.
[app]
log_level = "debug"
env = "dev"

# HTTP server.
[app.server]
name = "artemis"
address = "0.0.0.0:9009"
socket = ""
read_timeout = "5s"
write_timeout = "5s"
max_body_size = 10000000
keepalive_timeout = "10s"

# Upload.
[upload]
provider = "s3"

[upload.localfs]
upload_path = ""

[upload.s3]
url = ""
public_url = ""
access_key = ""
secret_key = ""
region = "ap-south-1"
bucket = "artemis"
bucket_path = ""
bucket_type = "private"
expiry = "15m"

[db]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "postgres"
database = "artemis"
ssl_mode = "disable"
max_open = 100
max_idle = 30
max_lifetime = "10s"

[redis]
address = "127.0.0.1:6379"
password = ""
db = 0

[message]
dispatch_concurrency = 10
dispatch_read_interval = "50ms"
incoming_queue_size = 10000
outgoing_queue_size = 10000

[notification]
concurrency = 2
queue_size = 100