# App.
[app]
log_level = "debug"
env = "dev"

# HTTP server.
[app.server]
address = "0.0.0.0:9000"
socket = ""
read_timeout = "5s"
write_timeout = "5s"
max_body_size = 10000000
keepalive_timeout = "10s"

# File upload provider.
[upload]
provider = "fs"

# Filesytem provider.
[upload.fs]
upload_path = '/home/ubuntu/uploads'

# S3 provider.
[upload.s3]
url = ""
access_key = ""
secret_key = ""
region = "ap-south-1"
bucket = "bucket"
bucket_path = ""
expiry = "6h"

# Postgres.
[db]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "postgres"
database = "libredesk"
ssl_mode = "disable"
max_open = 30
max_idle = 30
max_lifetime = "300s"

# Redis.
[redis]
address = "127.0.0.1:6379"
password = ""
db = 0

[message]
outgoing_queue_workers = 10
incoming_queue_workers = 10
message_outoing_scan_interval = "50ms"
incoming_queue_size = 5000
outgoing_queue_size = 5000

[notification]
concurrency = 2
queue_size = 2000

[automation]
worker_count = 10

[autoassigner]
autoassign_interval = "5m"

[conversation]
unsnooze_interval = "5m"

[sla]
evaluation_interval = "5m"